language: ruby
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
bundler_args: --without development production --quiet
script:
  - "bundle exec rake test_app"
  - "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
gemfile:
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    - ecl1pse.armageddon@gmail.com
